name: kobi_pay_interview
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  fl_chart: ^1.1.0
  toastification: ^3.0.3
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  hooks_riverpod: ^3.0.3
  shimmer: ^3.0.0
  dio: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: open_sans
      fonts:
        - asset: fonts/open_sans/OpenSans-ExtraBold.ttf
        - asset: fonts/open_sans/OpenSans-SemiBold.ttf
        - asset: fonts/open_sans/OpenSans-Bold.ttf
        - asset: fonts/open_sans/OpenSans-Regular.ttf
        - asset: fonts/open_sans/OpenSans-Medium.ttf
        - asset: fonts/open_sans/OpenSans-Light.ttf
    - family: special_gothic
      fonts:
        - asset: fonts/special_gothic/SpecialGothicExpandedOne-Regular.ttf